#! /bin/sh


# bspc monitor -d I II III IV V VI VII VIII IX X
bspc monitor -d 0001 0010 0011 0100 0101 0110 0111 1000 1001 0000
# bspc monitor DP1 -d XI

bspc config border_width          0
bspc config window_gap            22
bspc config active_border_color   '#612f5f'
bspc config normal_border_color   '#263a41'
bspc config focused_border_color  '#612f5f'
bspc config split_ratio           0.50
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config focus_follows_pointer true
bspc config bottom_padding        24

#bspc rule -a Firefox desktop='^3' follow=on
#bspc rule -a Gimp desktop='^8' follow=on
#bspc rule -a URxvt:main desktop=^1
#bspc rule -a URxvt:ranger desktop=^4
#bspc rule -a URxvt:ncmpcpp desktop=^2
#bspc rule -a URxvt:cava desktop=^2 split_dir=south
#bspc rule -a URxvt:newsbeuter floating=off desktop=^6
#bspc rule -a URxvt:rtorrent desktop=^9
#bspc rule -a URxvt:cprogram desktop=^4

# auto start
sxhkd &
compton -b
feh --bg-fill /HD/FS/Picture/WallPaper/assassin_awesome.png
conky -c ~/.config/conky/conky.conf
stalonetray --dockapp-mode simple &
qxkb &
nm-applet &
dunst &
mpd &
wmname LG3D

#urxvt -name main -title main &
#urxvt -name ncmpcpp -title ncmpcpp -e ncmpcpp &
#urxvt -name cava -title cava -e cava &
